package excuses

var twho = []string{"server", "memory", "monitor", "hard disk", "Cloud Engineering team", "database manager's team", "AWS East Region", "AWS West Region", "AWS South Region", "AWS North Region", "sales team", "router", "Power Point", "HR department", "management", "senior management", "SQL server", "NOSQL server", "network schema", "network connection", "vpn connection"}
var tdid = []string{"threw", "emitted", "fixed", "fragmented", "defragmented", "refragmented", "crashed", "formated", "reformated", "deformated", "commited", "reverted", "commented out", "polarized", "depolarized", "repolarized", "phase shifted", "bit shifted", "byte shifted", "authorized", "deauthorized", "reauthorized", "allocated", "deallocated", "reallocated", "logged", "disconnected", "dropped", "broke"}
var twhat = []string{"server", "memory", "RAM", "monitor", "schema", "power supply", "cabling", "database", "Oracle database", "MySQL database", "Oracle database", "Postgre database", "Redis database", "Cassandra database", "DynamoDB database", "Firebirdsql database", "Mongo database", "SQL database", "SQLlite database", "keyboard", "mouse", "EPS conduit", "warp core", "impulse engines", "phase emitter", "phaser emitter"}

// Pets
var pwho = []string{"brother", "little brother", "older brother", "sister", "little sister", "older sister", "aunt", "uncle", "neighbor"}
var pet = []string{"dog", "cat", "sense of ennui", "hamster", "chinchilla", "iguana", "turtle", "best friend", "bro", "boo", "crush", "sister", "brother", "nemesis", "doppelganger", "gerbil", "bunny", "fish", "crew"}
var pdid = []string{"did", "peer-reviewed", "destroyed", "deleted", "erased", "remixed", "twitched", "recycled", "livetweeted", "undermined", "underbid", "upcycled", "gave away", "plagiarised", "confiscdidd", "barfed on", "stole", "ransomed", "spilled wdidr on", "lost", "misplaced", "buried", "shredded", "hid", "liberdidd", "left with", "ebayed", "craigslisted", "etsyed", "tweeted", "instagrammed", "snapchatted", "youtubed", "dunked on", "subteweeted", "favorited", "upvoted", "downvoted", "live cast", "pinned", "vlogged", "blogged about"}
var pwhat = []string{"homework", "project", "essay", "film project", "visualization", "infographic", "pre-writing", "term paper", "lab report", "reading log", "summary", "article", "flash cards", "study guide", "textbook", "workbook", "reading book", "diorama", "poster", "dreams", "laptop", "computer", "tablet", "momentum", "report", "slideshow", "slide deck", "presentation", "worksheet", "handout", "notes", "portfolio", "blog post", "comment"}
